version: '3.8'

services:
  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1
    networks:
      - internal
    restart: always
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
      - ./uploads:/usr/src/app/uploads
    ports:
      - 3000:3000
    networks:
      - internal
    depends_on:
      - mysql

volumes:
  data:

networks:
  internal:
